version: '3.8'
services:
  # nginx
  gg-nginx:
    container_name: gg-nginx-container
    image: nginx:stable-alpine
    ports:
      - "${NGINX_TO_PORT}:${NGINX_FROM_PORT}"
      - "${NGINX_TO_PORT_SSL}:${NGINX_FROM_PORT_SSL}"
    volumes:
      - ./src:/var/www/gg
      - ./_docker/nginx/${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - gg-php_8.2
      - gg-mariadb
    networks:
      - gg

  #php
  gg-php_8.2:
    container_name: gg-php-8-container
    build:
      context: .
      dockerfile: ./_docker/php/php.dockerfile
    volumes:
      - ./src/:/var/www/gg
      - ./_docker/php/php.ini:/usr/local/etc/php/php.ini
    command: php-fpm
    depends_on:
      - gg-mariadb
    ports:
      - "3004:3004"
    networks:
      - gg

  #mysql
  gg-mariadb:
    container_name: gg-mariadb-container
    image: mariadb:latest
    ports:
      - "${DB_TO_PORT}:${DB_FROM_PORT}"
    volumes:
      - ./_docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: gg
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - gg

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - gg-mariadb:db
    restart: always
    ports:
      - "3002:80"
    environment:
      UPLOAD_LIMIT: 500M
      PMA_ARBITRARY: 1
    networks:
      - gg

  certbot:
    image: certbot/certbot
    container_name: certbot
#    ports:
#      - "6000:80"
#    env_file:
#      - .env
    # и снова мониторуем директорию nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${DOMAIN_EMAIL} -d gg-hub.ru -d admin.gg-hub.ru -d tl.gg-hub.ru --agree-tos
#    command: certonly --manual --preferred-challenges=dns --email ${DOMAIN_EMAIL} --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d ${DOMAIN_URL} -d *.${DOMAIN_URL}
    depends_on:
      - gg-nginx
    networks:
      - gg

networks:
  gg: